export const Events = {
  JOIN_ROOM: 'join_room',
  LEAVE_ROOM: 'leave_room',
  SYNC_STATE: 'sync_state',
  PLAY: 'play',
  PAUSE: 'pause',
  SEEK: 'seek',
  CHANGE_VIDEO: 'change_video',
  ASSIGN_ROLE: 'assign_role',
  REMOVE_PARTICIPANT: 'remove_participant',
  USER_JOINED: 'user_joined',
  USER_LEFT: 'user_left',
  ROLE_ASSIGNED: 'role_assigned',
  PARTICIPANT_REMOVED: 'participant_removed',
  CHAT_MESSAGE: 'chat_message',
  REACTION: 'reaction',
  REQUEST_CHANGE: 'request_change',
  ACTION_REQUESTED: 'action_requested',
  APPROVE_REQUEST: 'approve_request',
  REJECT_REQUEST: 'reject_request',
  REQUEST_APPROVED: 'request_approved',
  REQUEST_REJECTED: 'request_rejected',
  ERROR: 'error'
};
